# Generated by Django 3.1.2 on 2020-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptype', models.CharField(blank=True, max_length=50, null=True)),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('pcontent', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
