/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-12-06 08:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hoewon_005fscm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/PRJ/CTeam/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cteam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/PRJ/CTeam/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cteam/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605487512181L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">    \r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Playfair+Display:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/fonts/icomoon/style.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/owl.carousel.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/owl.theme.default.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/jquery.fancybox.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/aos.css\">\r\n");
      out.write("  <script src=\"//code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("  slide();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 슬라이드 \r\n");
      out.write("function slide() {\r\n");
      out.write("  var wid = 0;\r\n");
      out.write("  var now_num = 0;\r\n");
      out.write("  var slide_length = 0;\r\n");
      out.write("  var auto = null;\r\n");
      out.write("  var $dotli = $('.dot>li');\r\n");
      out.write("  var $panel = $('.panel');\r\n");
      out.write("  var $panelLi = $panel.children('li');\r\n");
      out.write("\r\n");
      out.write("  // 변수 초기화\r\n");
      out.write("  function init() {\r\n");
      out.write("    wid = $('.slide').width();\r\n");
      out.write("    now_num = $('.dot>li.on').index();\r\n");
      out.write("    slide_length = $dotli.length;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 이벤트 묶음\r\n");
      out.write("  function slideEvent() {\r\n");
      out.write("\r\n");
      out.write("    // 슬라이드 하단 dot버튼 클릭했을때\r\n");
      out.write("    $dotli.click(function() {\r\n");
      out.write("      now_num = $(this).index();\r\n");
      out.write("      slideMove();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 이후 버튼 클릭했을때\r\n");
      out.write("    $('.next').click(function() {\r\n");
      out.write("      nextChkPlay();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 이전 버튼 클릭했을때\r\n");
      out.write("    $('.prev').click(function() {\r\n");
      out.write("      prevChkPlay();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 오토플레이\r\n");
      out.write("    autoPlay();\r\n");
      out.write("\r\n");
      out.write("    // 오토플레이 멈춤\r\n");
      out.write("    autoPlayStop();\r\n");
      out.write("\r\n");
      out.write("    // 오토플레이 재시작\r\n");
      out.write("    autoPlayRestart();\r\n");
      out.write("\r\n");
      out.write("    // 화면크기 재설정 되었을때\r\n");
      out.write("    resize();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 자동실행 멈춤\r\n");
      out.write("  function autoPlayStop() {\r\n");
      out.write("    $panelLi.mouseenter(function() {\r\n");
      out.write("      clearInterval(auto);\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  // 자동실행 멈췄다가 재실행\r\n");
      out.write("  function autoPlayRestart() {\r\n");
      out.write("    $panelLi.mouseleave(function() {\r\n");
      out.write("      auto = setInterval(function() {\r\n");
      out.write("        nextChkPlay();\r\n");
      out.write("      }, 3000);\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 이전 버튼 클릭시 조건 검사후 슬라이드 무브\r\n");
      out.write("  function prevChkPlay() {\r\n");
      out.write("    if (now_num == 0) {\r\n");
      out.write("      now_num = slide_length - 1;\r\n");
      out.write("    } else {\r\n");
      out.write("      now_num--;\r\n");
      out.write("    }\r\n");
      out.write("    slideMove();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 이후 버튼 클릭시 조건 검사후 슬라이드 무브\r\n");
      out.write("  function nextChkPlay() {\r\n");
      out.write("    if (now_num == slide_length - 1) {\r\n");
      out.write("      now_num = 0;\r\n");
      out.write("    } else {\r\n");
      out.write("      now_num++;\r\n");
      out.write("    }\r\n");
      out.write("    slideMove();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 슬라이드 무브\r\n");
      out.write("  function slideMove() {\r\n");
      out.write("    $panel.stop().animate({\r\n");
      out.write("      'margin-left': -wid * now_num\r\n");
      out.write("    });\r\n");
      out.write("    $dotli.removeClass('on');\r\n");
      out.write("    $dotli.eq(now_num).addClass('on');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 화면크기 조정시 화면 재설정\r\n");
      out.write("  function resize() {\r\n");
      out.write("    $(window).resize(function() {\r\n");
      out.write("      init();\r\n");
      out.write("      $panel.css({\r\n");
      out.write("        'margin-left': -wid * now_num\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("  init();\r\n");
      out.write("  slideEvent();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#wrap{\r\n");
      out.write("background-image: URL('resources/images/img_1_sq.jpg'); \r\n");
      out.write("width: 450px;\r\n");
      out.write("margin: auto;\r\n");
      out.write("margin-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("#space {\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    width: 74%;\r\n");
      out.write("    margin-top: 117px;\r\n");
      out.write("}\r\n");
      out.write(".back{\r\n");
      out.write("background-image: URL('resources/images/img_1_sq.jpg'); \r\n");
      out.write("margin: auto;\r\n");
      out.write("width:450%;\r\n");
      out.write("height;\r\n");
      out.write("}\r\n");
      out.write(".login_div {\r\n");
      out.write("    background: rgb(120 130 110 / 75%);\r\n");
      out.write("    border-radius: -10px;\r\n");
      out.write("    height: 35vh;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: aliceblue;\r\n");
      out.write("}\r\n");
      out.write(".login_table{\r\n");
      out.write("\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write(".login_table tr td{\r\n");
      out.write("\tcolor: aliceblue;\r\n");
      out.write("    padding: 10;;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".login_p{\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul,\r\n");
      out.write("ol,\r\n");
      out.write("li {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("  vertical-align: top;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding-top: 50px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel {\r\n");
      out.write("  width: 400%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel>li {\r\n");
      out.write("  width: 25%;\r\n");
      out.write("  height: 200px;\r\n");
      out.write("  float: left;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-size: 100% 100%;\r\n");
      out.write("  font-size: 41px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel>li:nth-of-type(1) {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel>li:nth-of-type(2) {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel>li:nth-of-type(3) {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dot:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dot {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  bottom: 10%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dot>li {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 25px;\r\n");
      out.write("  height: 25px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  margin-left: 10px;\r\n");
      out.write("  margin-right: 10px;\r\n");
      out.write("  text-indent: -9999px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dot>li.on {\r\n");
      out.write("  background-color: #342f2f;\r\n");
      out.write("}\r\n");
      out.write(".col-lg-6 {\r\n");
      out.write("    -webkit-box-flex: 0;\r\n");
      out.write("    -ms-flex: 0 0 50%;\r\n");
      out.write("    flex: 48 35 50%;\r\n");
      out.write("    max-width: auto;\r\n");
      out.write("    max-height: 150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\t\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t \t<title>회원가입</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<body data-spy=\"scroll\" data-target=\".site-navbar-target\" data-offset=\"300\" >\r\n");
      out.write("\t\r\n");
      out.write("\t  <div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"site-mobile-menu site-navbar-target\">\r\n");
      out.write("      <div class=\"site-mobile-menu-header\">\r\n");
      out.write("        <div class=\"site-mobile-menu-close mt-3\">\r\n");
      out.write("          <span class=\"icon-close2 js-menu-toggle\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t <header class=\"site-navbar light js-sticky-header site-navbar-target\" role=\"banner\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-6 col-xl-2\">\r\n");
      out.write("            <div class=\"mb-0 site-logo\"><a href=\"index.do\" class=\"mb-0\">정부노인지원<span class=\"text-primary\">.</span> </a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-12 col-md-10 d-none d-xl-block\">\r\n");
      out.write("            <nav class=\"site-navigation position-relative text-right\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"site-menu main-menu js-clone-nav mr-auto d-none d-lg-block\">\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                <li><a href=\"index.do\" class=\"active nav-link\">Home</a></li>\r\n");
      out.write("                <li class=\"has-children\">\r\n");
      out.write("                  <a href=\"apply_services_en.do\" class=\"nav-link\">도우미 서비스</a>\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"apply_services_en.do\" class=\"nav-link\">서비스 소개</a></li>\r\n");
      out.write("                    <li><a href=\"apply_services_type_en.do\" class=\"nav-link\">서비스 신청하기</a></li>\r\n");
      out.write("\t\t\t\t\t <li class=\"has-children\">\r\n");
      out.write("                    <a href=\"#\">도우미 지원하기</a>\r\n");
      out.write("                      <ul class=\"dropdown\">\r\n");
      out.write("                        <li><a href=\"guide_Life_apply_yj.do\">생활도우미 지원하기</a></li>\r\n");
      out.write("                        <li><a href=\"guide_nursing_apply_yj.do\">간병인도우미 지원하기</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"has-children\">\r\n");
      out.write("                  <a href=\"voice_service_intro_dy.do\" class=\"nav-link\">음성인식 서비스</a>\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"voice_service_intro_dy.do\" class=\"nav-link\">서비스 소개</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"has-children\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">커뮤니티 서비스</a>\r\n");
      out.write("                  <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"communityService.do\" class=\"nav-link\">친구위치 검색</a></li>\r\n");
      out.write("                    <li class=\"has-children\">\r\n");
      out.write("                      <a href=\"#\">커뮤니티 공간 정보</a>\r\n");
      out.write("                      <ul class=\"dropdown\">\r\n");
      out.write("                        <li><a href=\"medicalLocation.do\">의료복지시설</a></li>\r\n");
      out.write("                        <li><a href=\"silverhallLocation.do\">재가노인복지시설</a></li>\r\n");
      out.write("                        <li><a href=\"elderlyhomeLocation.do\">요양시설</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"bus_service.do\" class=\"nav-link\">노약자 교통정보</a></li>\r\n");
      out.write("                <li><a href=\"contact.do\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("           </div> \r\n");
      out.write("   <div class=\"col-6 d-inline-block d-xl-none ml-md-0 py-3\" style=\"position: relative; top: 3px;\"><a href=\"#\" class=\"site-menu-toggle js-menu-toggle float-right\"><span class=\"icon-menu h3 text-white\"></span></a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"slide-item overlay\" style=\"background-image: url('resources/images/slider-1.jpg')\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("          <div class=\"login_div\">\r\n");
      out.write("           <table class=\"login_table\">\r\n");
      out.write("\t\t<h3>회원가입</h3>\r\n");
      out.write("<div class=\"slide\">\r\n");
      out.write("\t <ul class=\"panel\">\t    \r\n");
      out.write("\t    <li>이름을입력하세요.<input type=\"text\" name=\"name\"></li>\r\n");
      out.write("\t    <li>아이디를입력하세요.<input type=\"text\" name=\"id\"> </li>\r\n");
      out.write("\t    <li>비밀번호를입력하세요.<input type=\"password\" name=\"pwd\"></li>\r\n");
      out.write("\t    <li>성별선택바랍니다. <select name=\"sex\">\r\n");
      out.write("\t    <option value=\"\">성별선택</option>\r\n");
      out.write("\t    <option value=\"\">남자</option>\r\n");
      out.write("\t    <option value=\"\">여자</option>\r\n");
      out.write("\t    </select></li>\r\n");
      out.write("\t\t<li>휴대전화를 입력하세요.<select name=\"Phone\">\r\n");
      out.write("\t    <option value=\"\">-선택-</option>\r\n");
      out.write("\t    <option value=\"\">010</option>\r\n");
      out.write("\t\t<option value=\"\">011</option>\r\n");
      out.write("\t\t<option value=\"\">014</option>\r\n");
      out.write("\t\t<option value=\"\">016</option>\r\n");
      out.write("\t\t</select></li>\r\n");
      out.write("\t\t<li>주소를입력하세요.<input type=\"text\" name=\"addr\"></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"dot\">\r\n");
      out.write("\t    <li class=\"on\">이름</li>\r\n");
      out.write("\t    <li>아이디</li>\r\n");
      out.write("\t    <li>비밀번호</li>\r\n");
      out.write("\t    <li>성별</li>\r\n");
      out.write("\t    <li>전화번호</li>\r\n");
      out.write("\t    <li>1</li>\r\n");
      out.write("\t    <li>1</li>\r\n");
      out.write("\t    <li>1</li>\r\n");
      out.write("\t    \r\n");
      out.write("\t </ul>     \r\n");
      out.write("       </div> \r\n");
      out.write("           </table>\r\n");
      out.write("        \t</div>            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"site-footer bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <h2 class=\"footer-heading mb-4\">About</h2>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi cumque tenetur inventore veniam, hic vel ipsa necessitatibus ducimus architecto fugiat!</p>\r\n");
      out.write("            <div class=\"my-5 social\">\r\n");
      out.write("              <a href=\"#\" class=\"pl-0 pr-3\"><span class=\"icon-facebook\"></span></a>\r\n");
      out.write("              <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-twitter\"></span></a>\r\n");
      out.write("              <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-instagram\"></span></a>\r\n");
      out.write("              <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-linkedin\"></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-8\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-4\">\r\n");
      out.write("                <h2 class=\"footer-heading mb-4\">Quick Links</h2>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li><a href=\"#\">Amazing Atmosphere</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Caring Staff</a></li>\r\n");
      out.write("                  <li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("                  <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-4\">\r\n");
      out.write("                <h2 class=\"footer-heading mb-4\">Helpful Link</h2>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li><a href=\"#\">Hospice Care</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Excellent Cuisine</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Privacy</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Terms</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-4\">\r\n");
      out.write("                <h2 class=\"footer-heading mb-4\">Resources</h2>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li><a href=\"#\">Health Care</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Elderly Care</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Care with Love</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Quality Care</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"border-top pt-5\">\r\n");
      out.write("              <p class=\"copyright\"><small>\r\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart text-danger\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\" >Colorlib</a>\r\n");
      out.write("                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></small></p>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
